// countries.ts

export const countries = [
  { name: 'United States', code: 'America/New_York' },
  { name: 'United Kingdom', code: 'Europe/London' },
  { name: 'Canada', code: 'America/Toronto' },
  { name: 'Australia', code: 'Australia/Sydney' },
  { name: 'Germany', code: 'Europe/Berlin' },
  { name: 'Japan', code: 'Asia/Tokyo' },
  { name: 'France', code: 'Europe/Paris' },
  { name: 'Italy', code: 'Europe/Rome' },
  { name: 'Spain', code: 'Europe/Madrid' },
  { name: 'China', code: 'Asia/Shanghai' },
  { name: 'India', code: 'Asia/Kolkata' },
  { name: 'Brazil', code: 'America/Sao_Paulo' },
  { name: 'Mexico', code: 'America/Mexico_City' },
  { name: 'South Korea', code: 'Asia/Seoul' },
  { name: 'Russia', code: 'Europe/Moscow' },
  { name: 'Turkey', code: 'Europe/Istanbul' },
  { name: 'Indonesia', code: 'Asia/Jakarta' },
  { name: 'Netherlands', code: 'Europe/Amsterdam' },
  { name: 'Saudi Arabia', code: 'Asia/Riyadh' },
  { name: 'Switzerland', code: 'Europe/Zurich' },
  { name: 'Sweden', code: 'Europe/Stockholm' },
  { name: 'Norway', code: 'Europe/Oslo' },
  { name: 'Denmark', code: 'Europe/Copenhagen' },
  { name: 'Finland', code: 'Europe/Helsinki' },
  { name: 'Belgium', code: 'Europe/Brussels' },
  { name: 'Poland', code: 'Europe/Warsaw' },
  { name: 'Austria', code: 'Europe/Vienna' },
  { name: 'Argentina', code: 'America/Argentina/Buenos_Aires' },
  { name: 'South Africa', code: 'Africa/Johannesburg' },
  { name: 'Greece', code: 'Europe/Athens' },
  { name: 'Portugal', code: 'Europe/Lisbon' },
  { name: 'Singapore', code: 'Asia/Singapore' },
  { name: 'Egypt', code: 'Africa/Cairo' },
  { name: 'Vietnam', code: 'Asia/Ho_Chi_Minh' },
  { name: 'Thailand', code: 'Asia/Bangkok' },
  { name: 'Iran', code: 'Asia/Tehran' },
  { name: 'United Arab Emirates', code: 'Asia/Dubai' },
  { name: 'Israel', code: 'Asia/Jerusalem' },
  { name: 'Malaysia', code: 'Asia/Kuala_Lumpur' },
  { name: 'Philippines', code: 'Asia/Manila' },
  { name: 'Colombia', code: 'America/Bogota' },
  { name: 'Chile', code: 'America/Santiago' },
  { name: 'Pakistan', code: 'Asia/Karachi' },
  { name: 'Bangladesh', code: 'Asia/Dhaka' },
  { name: 'Nigeria', code: 'Africa/Lagos' },
  { name: 'Czech Republic', code: 'Europe/Prague' },
  { name: 'Romania', code: 'Europe/Bucharest' },
  { name: 'Ukraine', code: 'Europe/Kiev' },
  { name: 'Hungary', code: 'Europe/Budapest' },
  { name: 'Ireland', code: 'Europe/Dublin' },
  { name: 'New Zealand', code: 'Pacific/Auckland' },
  { name: 'Algeria', code: 'Africa/Algiers' },
  { name: 'Morocco', code: 'Africa/Casablanca' },
  { name: 'Iraq', code: 'Asia/Baghdad' },
  { name: 'Peru', code: 'America/Lima' },
  { name: 'Venezuela', code: 'America/Caracas' },
  { name: 'Ecuador', code: 'America/Guayaquil' },
  { name: 'Kenya', code: 'Africa/Nairobi' },
  { name: 'Tanzania', code: 'Africa/Dar_es_Salaam' },
  { name: 'Ghana', code: 'Africa/Accra' },
  { name: 'Cameroon', code: 'Africa/Douala' },
  { name: 'Uganda', code: 'Africa/Kampala' },
  { name: 'Zimbabwe', code: 'Africa/Harare' },
  { name: 'Senegal', code: 'Africa/Dakar' },
  { name: 'Mali', code: 'Africa/Bamako' },
  { name: 'Cote d\'Ivoire', code: 'Africa/Abidjan' },
  { name: 'Angola', code: 'Africa/Luanda' },
  { name: 'Madagascar', code: 'Indian/Antananarivo' },
  { name: 'Niger', code: 'Africa/Niamey' },
  { name: 'Mozambique', code: 'Africa/Maputo' },
  { name: 'Ethiopia', code: 'Africa/Addis_Ababa' },
  { name: 'Tunisia', code: 'Africa/Tunis' },
  { name: 'Yemen', code: 'Asia/Aden' },
  { name: 'Lebanon', code: 'Asia/Beirut' },
  { name: 'Jordan', code: 'Asia/Amman' },
  { name: 'Oman', code: 'Asia/Muscat' },
  { name: 'Kuwait', code: 'Asia/Kuwait' },
  { name: 'Qatar', code: 'Asia/Qatar' },
  { name: 'Bahrain', code: 'Asia/Bahrain' },
  { name: 'Bahamas', code: 'America/Nassau' },
  { name: 'Barbados', code: 'America/Barbados' },
  { name: 'Bermuda', code: 'Atlantic/Bermuda' },
  { name: 'Cuba', code: 'America/Havana' },
  { name: 'Dominican Republic', code: 'America/Santo_Domingo' },
  { name: 'Jamaica', code: 'America/Jamaica' },
  { name: 'Puerto Rico', code: 'America/Puerto_Rico' },
  { name: 'Trinidad and Tobago', code: 'America/Port_of_Spain' },
  { name: 'Honduras', code: 'America/Tegucigalpa' },
  { name: 'Costa Rica', code: 'America/Costa_Rica' },
  { name: 'Nicaragua', code: 'America/Managua' },
  { name: 'Guatemala', code: 'America/Guatemala' },
  { name: 'El Salvador', code: 'America/El_Salvador' },
  { name: 'Panama', code: 'America/Panama' },
  { name: 'Belize', code: 'America/Belize' },
  { name: 'Guyana', code: 'America/Guyana' },
  { name: 'Suriname', code: 'America/Paramaribo' },
  { name: 'French Guiana', code: 'America/Cayenne' },
  { name: 'Saint Lucia', code: 'America/St_Lucia' },
  { name: 'Saint Vincent and the Grenadines', code: 'America/St_Vincent' },
  { name: 'Antigua and Barbuda', code: 'America/Antigua' },
  { name: 'Grenada', code: 'America/Grenada' },
  { name: 'Saint Kitts and Nevis', code: 'America/St_Kitts' },
];
